version: '3'

services:
  <%= composeName %>:
    build: ./
    volumes:
      - ./:/app
    ports:
      - '4000:4000'
    variables:
      DATABASE_URL: postgresql://postgres:password@db:5432/postgres
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password